"""add onboarding tables

Revision ID: 3dbac43ae1ea
Revises: 6bca8731b062
Create Date: 2026-07-18 18:35:20.093337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbac43ae1ea'
down_revision: Union[str, Sequence[str], None] = '6bca8731b062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('answer_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_responses_question_key'), 'onboarding_responses', ['question_key'], unique=False)
    op.create_index(op.f('ix_onboarding_responses_user_id'), 'onboarding_responses', ['user_id'], unique=False)
    op.create_table('user_personas',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('primary_goal', sa.String(length=100), nullable=True),
    sa.Column('main_challenge', sa.String(length=100), nullable=True),
    sa.Column('income_type', sa.String(length=100), nullable=True),
    sa.Column('pay_frequency', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.String(length=100), nullable=True),
    sa.Column('behaviour_pattern', sa.String(length=100), nullable=True),
    sa.Column('spending_trigger', sa.String(length=100), nullable=True),
    sa.Column('coaching_style', sa.String(length=100), nullable=True),
    sa.Column('setup_preferences', sa.String(length=100), nullable=True),
    sa.Column('thirty_day_win', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('user_personas')
    op.drop_index(op.f('ix_onboarding_responses_user_id'), table_name='onboarding_responses')
    op.drop_index(op.f('ix_onboarding_responses_question_key'), table_name='onboarding_responses')
    op.drop_table('onboarding_responses')
    # ### end Alembic commands ###
